export const books = [
  { 
    id: "001",
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    category: "Fiction",
    rating: 4.4,
    description: "A classic novel of pre-colonial life in Nigeria and the impact of European colonialism on African culture.",
    imageLink: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=1374&auto=format&fit=crop",
  },
  { 
    id: "002",
    title: "Fairy Tales",
    author: "Hans Christian Andersen",
    category: "Fantasy",
    rating: 4.2,
    description: "A beloved collection of fairy tales that have enchanted children and adults for generations.",
    imageLink: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=1374&auto=format&fit=crop",
  },
  { 
    id: "003",
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    category: "Classic",
    rating: 4.6,
    description: "An epic poem describing the journey through Hell, Purgatory, and Paradise, exploring themes of redemption and faith.",
    imageLink: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?q=80&w=1374&auto=format&fit=crop",
  },
  { 
    id: "004",
    title: "The Epic Of Gilgamesh",
    author: "Unknown",
    category: "Fiction",
    rating: 4.1,
    description: "One of the earliest works of literature, recounting the adventures of the legendary Sumerian king Gilgamesh.",
    imageLink: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?q=80&w=1429&auto=format&fit=crop",
  },
  { 
    id: "005",
    title: "The Book Of Job",
    author: "Unknown",
    category: "Philosophy",
    rating: 4.0,
    description: "A profound biblical text exploring themes of suffering, faith, and divine justice.",
    imageLink: "https://images.unsplash.com/photo-1588666309990-d68f08e3d4a6?q=80&w=1370&auto=format&fit=crop",
  },
  { 
    id: "006",
    title: "One Thousand and One Nights",
    author: "Unknown",
    category: "Fantasy",
    rating: 4.3,
    description: "A collection of Middle Eastern folk tales told by Scheherazade, including Aladdin and Sinbad.",
    imageLink: "https://images.unsplash.com/photo-1562232573-0305012a8818?q=80&w=1470&auto=format&fit=crop",
  },
  { 
    id: "007",
    title: "Njál's Saga",
    author: "Unknown",
    category: "Classic",
    rating: 4.2,
    description: "A medieval Icelandic saga chronicling blood feuds, honor, and law in Viking society.",
    imageLink: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=1374&auto=format&fit=crop",
  },
  { 
    id: "008",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Fiction",
    rating: 4.8,
    description: "A witty and romantic novel about manners, marriage, and social standing in 19th-century England.",
    imageLink: "https://images.unsplash.com/photo-1467951591042-f388365db261?q=80&w=1470&auto=format&fit=crop",
  },
  { 
    id: "009",
    title: "Le Père Goriot",
    author: "Honoré de Balzac",
    category: "Classic",
    rating: 4.1,
    description: "A powerful tale of ambition, love, and society in post-revolutionary Paris.",
    imageLink: "https://images.unsplash.com/photo-1554672053-c4205442a9fb?q=80&w=1470&auto=format&fit=crop",
  },
  { 
    id: "010",
    title: "Molloy, Malone Dies, The Unnamable",
    author: "Samuel Beckett",
    category: "Fiction",
    rating: 3.9,
    description: "A trilogy of experimental novels exploring existentialism, identity, and the absurd.",
    imageLink: "https://images.unsplash.com/photo-1599893242842-1b723407f8c9?q=80&w=1469&auto=format&fit=crop",
  },
  {
    id: "011",
    title: "1984",
    author: "George Orwell",
    category: "Dystopian",
    rating: 4.7,
    description: "A chilling prophecy about the future, totalitarianism and surveillance.",
    imageLink: "https://covers.openlibrary.org/b/id/7222246-L.jpg"
  },
  {
    id: "012",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    category: "Dystopian",
    rating: 4.6,
    description: "A firefighter who burns books meets a revolutionary who dares to read them.",
    imageLink: "https://covers.openlibrary.org/b/id/7984916-L.jpg"
  },
  {
    id: "013",
    title: "Moby-Dick",
    author: "Herman Melville",
    category: "Classic",
    rating: 4.2,
    description: "Captain Ahab’s obsessive quest to take revenge on the white whale.",
    imageLink: "https://covers.openlibrary.org/b/id/7222276-L.jpg"
  },
  {
    id: "014",
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    category: "Fantasy",
    rating: 4.7,
    description: "Seven fantasy novels for children that explore good vs. evil in Narnia.",
    imageLink: "https://covers.openlibrary.org/b/id/7222274-L.jpg"
  },
  {
    id: "015",
    title: "Frankenstein",
    author: "Mary Shelley",
    category: "Dystopian",
    rating: 4.4,
    description: "A scientist creates a sapient creature and abandons it to its fate.",
    imageLink: "https://covers.openlibrary.org/b/id/7222171-L.jpg"
  },
  {
    id: "016",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    category: "Fantasy",
    rating: 4.8,
    description: "A young prince’s journey through space and reflections on life and human nature.",
    imageLink: "https://covers.openlibrary.org/b/id/7182161-L.jpg"
  },
  {
    id: "017",
    title: "Faust",
    author: "Johann Wolfgang von Goethe",
    category: "Dystopian",
    rating: 4.5,
    description: "A dramatic poem about a scholar who makes a pact with the devil, exploring themes of ambition, knowledge, and salvation.",
    imageLink: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=1374&auto=format&fit=crop",
  },
  {
  id: "018",
  title: "The Brothers Karamazov",
  author: "Fyodor Dostoevsky",
  category: "Philosophy",
  rating: 4.7,
  description: "A profound exploration of faith, doubt, and morality through the lives of three very different brothers.",
  imageLink: "https://images.unsplash.com/photo-1544716278-e513176f20b5?q=80&w=1370&auto=format&fit=crop",
  },
  {
  id: "019",
  title: "Meditations",
  author: "Marcus Aurelius",
  category: "Philosophy",
  rating: 4.5,
  description: "A timeless collection of personal writings by the Roman emperor on Stoic philosophy and inner peace.",
  imageLink: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1370&auto=format&fit=crop",
  },
  {
  id: "020",
  title: "Walden",
  author: "Henry David Thoreau",
  category: "Philosophy",
  rating: 4.4,
  description: "A reflection on simple living in natural surroundings, emphasizing self-reliance and personal introspection.",
  imageLink: "https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=1370&auto=format&fit=crop",
  },
];